# Generated by Django 5.0 on 2024-01-17 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_slug_alter_articlescategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name_plural': 'Article Images'},
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='articles.articleimage', verbose_name='Article Image'),
        ),
    ]
