# Generated by Django 5.0 on 2024-01-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=models.CharField(blank=True, max_length=255, null=True), unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=models.CharField(blank=True, max_length=255, null=True), unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=models.CharField(blank=True, max_length=255, null=True), unique=True),
        ),
    ]
