# Generated by Django 5.0 on 2024-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banner_slug_alter_clients_slug_alter_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clients',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=''),
        ),
    ]
