# Generated by Django 5.0 on 2024-01-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='main_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productitem_main_image', to='core.productimage'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='productitem_images', to='core.productimage'),
        ),
    ]
