# Generated by Django 5.0 on 2024-01-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_banner_slug_alter_clients_slug_alter_team_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
