# Generated by Django 5.0 on 2024-02-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contact_user_alter_productitem_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='is_deletable',
            field=models.BooleanField(default=False),
        ),
    ]
