# Generated by Django 5.0 on 2024-02-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_featured_is_deletable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychoose',
            name='item',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Aboutitem',
        ),
        migrations.DeleteModel(
            name='Whychoose',
        ),
        migrations.DeleteModel(
            name='Whychooseitem',
        ),
    ]
