# Generated by Django 5.0 on 2024-02-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_whychoose_item_delete_about_delete_aboutitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now_add=True, default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.DeleteModel(
            name='Serviceitem',
        ),
    ]
