# Generated by Django 5.0 on 2024-08-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_service_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
