# Generated by Django 5.0 on 2024-01-09 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Productitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_main', models.ImageField(upload_to='product/', verbose_name='Product Image')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('price', models.PositiveBigIntegerField(verbose_name='Product Price')),
                ('old_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Product Old Price')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='products.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name_plural': 'Product Item',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_left', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('background_right', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('item', models.ManyToManyField(to='products.productitem')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('rate', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.review', verbose_name='Product Review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitem')),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
                'ordering': ('-created',),
            },
        ),
    ]
