# Generated by Django 5.0 on 2023-12-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='background',
            new_name='background_one',
        ),
        migrations.AddField(
            model_name='products',
            name='background_two',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
